=== compspec/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema for the definitions of the known labels",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "$comment": "Version of the compatibility spec",
      "type": "string"
    },
    "kind": {
      "$comment": "kind of compatibility spec",
      "type": "string"
    },
    "metadata": {
      "$comment": "metadata for the compatiblity spec",
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "compatibilities": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name", "version", "schema", "attributes"],
        "properties": {
          "name": {
            "$comment": "Name of the compatibility schema",
            "type": "string"
          },
          "version": {
            "$comment": "Version of the compatibility schema",
            "type": "string"
          },
          "schema": {
            "$comment": "web accessible public URL of the compatibility schema compspec.json",
            "type": "string"
          },
          "attributes": {
            "$comment": "Key value pairs for a given namespace.",
            "type": "object",
            "properties": {
              "patternProperties": {
                "\\w[\\w-]*": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== compspec/schemas/example/compatibility-spec.json
{
  "version": "0.0.0",
  "kind": "CompatibilitySpec",
  "metadata": {
    "name": "lammps-prototype"
  },
  "compatibilities": [
    {
      "name": "io.archspec",
      "version": "0.0.0",
      "schema": "https://raw.githubusercontent.com/supercontainers/compspec/main/archspec/compspec.json",
      "attributes": {
        "cpu.model": "13th Gen Intel(R) Core(TM) i5-1335U",
        "cpu.target": "amd64",
        "cpu.vendor": "GenuineIntel"
      }
    },
    {
      "name": "org.supercontainers",
      "version": "0.0.0",
      "schema": "https://raw.githubusercontent.com/supercontainers/compspec/main/supercontainers/compspec.json",
      "attributes": {
        "mpi.implementation": "mpich",
        "mpi.version": "4.1.1",
        "os.name": "Ubuntu 22.04.3 LTS",
        "os.release": "22.04.3",
        "os.vendor": "ubuntu",
        "os.version": "22.04",
        "hardware.gpu.available": "yes"
      }
    }
  ]
}
